services:
  db:
    image: mysql:8.0
    container_name: ${DB_CN_CINEMA}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d

  server:
    build: ./python
    container_name: python_server
    ports:
      - "5000:5000"
    environment:
      DB_CN_CINEMA: ${DB_CN_CINEMA}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
